â¶services:
  - type: web
    name: AashthaMusic
    env: python
    region: singapore
    plan: free
    pythonVersion: 3.11.9
    buildCommand: >-
      apt-get update && 
      apt-get install -y ffmpeg build-essential && 
      pip install --upgrade pip && 
      pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    branch: main
